### ISSUE TITLE
Xu：

### ISSUE THREAD

**Issue by xuliang0909** [TriHuynh00/AC3R-Demo#2]
1. First, I unpacked BeaNG.research in the \Users\Documents\ directory and renamed it to BeamNG.drive. Finally, I configured the system environment according to the steps of README.md.
![3](https://user-images.githubusercontent.com/45282116/65236100-732d1100-db0a-11e9-823d-94727b312c08.png)
![1](https://user-images.githubusercontent.com/45282116/65236254-c99a4f80-db0a-11e9-90ea-8f44b5197d33.png)

2. Then, during the process of running StartAC3R.bat, I encountered an error. After my debugging, it was not successful. The error log is the log.txt file I submitted.
![error](https://user-images.githubusercontent.com/45282116/65327156-c0ca7c00-dbe5-11e9-8e68-524bd7b7cead.png)
![2](https://user-images.githubusercontent.com/45282116/65236118-7c1de280-db0a-11e9-923d-f7178a47bdad.png)
# [log.txt](https://github.com/SoftLegend/AC3R-Demo/files/3630675/log.txt)

I would like to ask you, after downloading the compressed file from the official website, how do you build AC3R on BeaNG.research, can you tell me the specific steps if it is convenient? I followed the steps of README.md on github, but unfortunately I failed.

**Comment by SoftLegend** [comment]
The scenario could not be loaded because we need the base map file. I cannot upload the base map in Github because according to one BeamNG staff, this could violate copyright. However, I will try to post the map as a mod, or write a tutorial on how to do it, so anyone can download/create the base map it in the future when they have BeamNG.

The base map name is **smallgrid**, you need to unzip the smallgrid.zip file in C:\Users\[your_username]\Documents\BeamNG.drive\levels\ 

After placing the base map in a specified location, the next step is to copy 3D objects from BeamNG west_coast_usa map to the base map. To do this, you need to copy the **buildings, road, shapes, and terrain folder** in[BeamNG_unlimited_research]\levels\west_coast_usa\art\ to the base map in C:\Users\[your_username]\Documents\BeamNG.drive\levels\smallgrid\art\ folder

I will update the instruction on how to get the smallgrid base map and copy-paste 3D objects from west_coast_usa map in BeamNG research on the README file in the near future.

**Comment by xuliang0909** [comment]
Hello, before that, I'd like to ask if the BeamNG. drive in'C: Users your_username Documents BeamNG. drive levels smallgrid art Folder'you mentioned is the one marked in the picture below.
![image](https://user-images.githubusercontent.com/45282116/66312059-7b76b000-e942-11e9-928e-aef5449d8501.png)

**Comment by SoftLegend** [comment]
Right, it is great that you point out the tech demo!

Perhaps you could try the following steps:
1. Copy the GridMap levels of the tech demo to C:\Users\[your_username]\Documents\BeamNG.drive\levels\.
2. Open BeamNG, press F11, the object panel appears on the right side of BeamNG. Delete the road, trees and other objects in the map, *except the ground plane and other folders*. 
3. Set the x, y, z coordinate of the ground plane to -300, -300, 0 respectively.
4. Set squareSize = 5, maxHeight = 1, baseTexSize and lightMapSize = 1024.
5. Change the grid terrain to grass or other terrain using BeamNG terrain tool.
6. Save the map

Then you load the map again, if a car can run on the ground, then congratulation. Otherwise, please tell me the problem.

**Comment by xuliang0909** [comment]
I opened BeamNG, but after I pressed F11, there was no object panel on the interface.
![image](https://user-images.githubusercontent.com/45282116/66316391-2b9be700-e94a-11e9-89c1-89d5ea6b6f18.png)

**Comment by SoftLegend** [comment]
Oh, I am sorry, you need to open the GridMap first, then after the map is loaded, you press F11.

**Comment by xuliang0909** [comment]
Thank you very much. I see what you mean.
